### ISSUE TITLE
[Enhancement] Add Tri-linear logos at the top of the landing page.

### ISSUE THREAD

**Issue by sprakash57** [sprakash57/webpack-react-saga#11]
Currently, the logo on the landing page looks like this -

![image](https://user-images.githubusercontent.com/38065786/96351030-88da8480-10d6-11eb-8b99-327bc7493c1c.png)

Now the requirement is to add two more SVG, one for webpack and one for redux-saga at the left and the right of the react logo. Thus the name is Webpack-React-Saga. It should look similar to the below mockup (ignore the grey border around the mockup)-

![image](https://user-images.githubusercontent.com/38065786/96351110-f090cf80-10d6-11eb-9022-4d1c47ef63d7.png)

Points to remember -
1. Size of other SVGs should match to the one already present. Check the CSS class 'logo'.
2. run `npm test` and all the test cases should pass.

**Comment by Toshiuk** [comment]
Assing me ;)

**Comment by sprakash57** [comment]
Thank you for offering your valuable time. I have assigned it to you.

**Comment by sprakash57** [comment]
PR has been merged. Thanks once again. Looking forward to working with you again. If you enjoyed your time here, a ⭐ to the repo would be highly appreciated.
